package CPSF.com.demo.model.constant;

import lombok.Getter;

import java.util.Arrays;
import java.util.Optional;

@Getter
public enum Country {
    // Europe
    ALBANIA("AL", "Albania", "+355"),
    ANDORRA("AD", "Andora", "+376"),
    AUSTRIA("AT", "Austria", "+43"),
    BELGIUM("BE", "Belgia", "+32"),
    BELARUS("BY", "Białoruś", "+375"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bośnia i Hercegowina", "+387"),
    BULGARIA("BG", "Bułgaria", "+359"),
    CROATIA("HR", "Chorwacja", "+385"),
    CYPRUS("CY", "Cypr", "+357"),
    MONTENEGRO("ME", "Czarnogóra", "+382"),
    CZECH_REPUBLIC("CZ", "Czechy", "+420"),
    DENMARK("DK", "Dania", "+45"),
    ESTONIA("EE", "Estonia", "+372"),
    FINLAND("FI", "Finlandia", "+358"),
    FRANCE("FR", "Francja", "+33"),
    GREECE("GR", "Grecja", "+30"),
    SPAIN("ES", "Hiszpania", "+34"),
    NETHERLANDS("NL", "Holandia", "+31"),
    IRELAND("IE", "Irlandia", "+353"),
    ICELAND("IS", "Islandia", "+354"),
    LIECHTENSTEIN("LI", "Liechtenstein", "+423"),
    LITHUANIA("LT", "Litwa", "+370"),
    LUXEMBOURG("LU", "Luksemburg", "+352"),
    LATVIA("LV", "Łotwa", "+371"),
    NORTH_MACEDONIA("MK", "Macedonia Północna", "+389"),
    MALTA("MT", "Malta", "+356"),
    MOLDOVA("MD", "Mołdawia", "+373"),
    MONACO("MC", "Monako", "+377"),
    GERMANY("DE", "Niemcy", "+49"),
    NORWAY("NO", "Norwegia", "+47"),
    POLAND("PL", "Polska", "+48"),
    PORTUGAL("PT", "Portugalia", "+351"),
    RUSSIA("RU", "Rosja", "+7"),
    ROMANIA("RO", "Rumunia", "+40"),
    SAN_MARINO("SM", "San Marino", "+378"),
    SERBIA("RS", "Serbia", "+381"),
    SLOVAKIA("SK", "Słowacja", "+421"),
    SLOVENIA("SI", "Słowenia", "+386"),
    SWITZERLAND("CH", "Szwajcaria", "+41"),
    SWEDEN("SE", "Szwecja", "+46"),
    TURKEY("TR", "Turcja", "+90"),
    UKRAINE("UA", "Ukraina", "+380"),
    VATICAN_CITY("VA", "Watykan", "+379"),
    HUNGARY("HU", "Węgry", "+36"),
    UNITED_KINGDOM("GB", "Wielka Brytania", "+44"),
    ITALY("IT", "Włochy", "+39"),

    // Americas
    ANTIGUA_AND_BARBUDA("AG", "Antigua i Barbuda", "+1-268"),
    ARGENTINA("AR", "Argentyna", "+54"),
    BAHAMAS("BS", "Bahamy", "+1-242"),
    BARBADOS("BB", "Barbados", "+1-246"),
    BELIZE("BZ", "Belize", "+501"),
    BOLIVIA("BO", "Boliwia", "+591"),
    BRAZIL("BR", "Brazylia", "+55"),
    CHILE("CL", "Chile", "+56"),
    COLOMBIA("CO", "Kolumbia", "+57"),
    COSTA_RICA("CR", "Kostaryka", "+506"),
    CUBA("CU", "Kuba", "+53"),
    DOMINICA("DM", "Dominika", "+1-767"),
    DOMINICAN_REPUBLIC("DO", "Dominikana", "+1-809"),
    ECUADOR("EC", "Ekwador", "+593"),
    EL_SALVADOR("SV", "Salwador", "+503"),
    GRENADA("GD", "Grenada", "+1-473"),
    GUATEMALA("GT", "Gwatemala", "+502"),
    GUYANA("GY", "Gujana", "+592"),
    HAITI("HT", "Haiti", "+509"),
    HONDURAS("HN", "Honduras", "+504"),
    JAMAICA("JM", "Jamajka", "+1-876"),
    CANADA("CA", "Kanada", "+1"),
    MEXICO("MX", "Meksyk", "+52"),
    NICARAGUA("NI", "Nikaragua", "+505"),
    PANAMA("PA", "Panama", "+507"),
    PARAGUAY("PY", "Paragwaj", "+595"),
    PERU("PE", "Peru", "+51"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts i Nevis", "+1-869"),
    SAINT_LUCIA("LC", "Saint Lucia", "+1-758"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent i Grenadyny", "+1-784"),
    SURINAME("SR", "Surinam", "+597"),
    TRINIDAD_AND_TOBAGO("TT", "Trynidad i Tobago", "+1-868"),
    UNITED_STATES("US", "Stany Zjednoczone", "+1"),
    URUGUAY("UY", "Urugwaj", "+598"),
    VENEZUELA("VE", "Wenezuela", "+58"),

    // Asia
    AFGHANISTAN("AF", "Afganistan", "+93"),
    SAUDI_ARABIA("SA", "Arabia Saudyjska", "+966"),
    ARMENIA("AM", "Armenia", "+374"),
    AZERBAIJAN("AZ", "Azerbejdżan", "+994"),
    BAHRAIN("BH", "Bahrajn", "+973"),
    BANGLADESH("BD", "Bangladesz", "+880"),
    BHUTAN("BT", "Bhutan", "+975"),
    MYANMAR("MM", "Birma (Mjanma)", "+95"),
    BRUNEI("BN", "Brunei", "+673"),
    CHINA("CN", "Chiny", "+86"),
    PHILIPPINES("PH", "Filipiny", "+63"),
    GEORGIA("GE", "Gruzja", "+995"),
    INDIA("IN", "Indie", "+91"),
    INDONESIA("ID", "Indonezja", "+62"),
    IRAQ("IQ", "Irak", "+964"),
    IRAN("IR", "Iran", "+98"),
    ISRAEL("IL", "Izrael", "+972"),
    JAPAN("JP", "Japonia", "+81"),
    YEMEN("YE", "Jemen", "+967"),
    JORDAN("JO", "Jordania", "+962"),
    CAMBODIA("KH", "Kambodża", "+855"),
    QATAR("QA", "Katar", "+974"),
    KAZAKHSTAN("KZ", "Kazachstan", "+7"),
    KYRGYZSTAN("KG", "Kirgistan", "+996"),
    SOUTH_KOREA("KR", "Korea Południowa", "+82"),
    NORTH_KOREA("KP", "Korea Północna", "+850"),
    KUWAIT("KW", "Kuwejt", "+965"),
    LAOS("LA", "Laos", "+856"),
    LEBANON("LB", "Liban", "+961"),
    MALDIVES("MV", "Malediwy", "+960"),
    MALAYSIA("MY", "Malezja", "+60"),
    MONGOLIA("MN", "Mongolia", "+976"),
    NEPAL("NP", "Nepal", "+977"),
    OMAN("OM", "Oman", "+968"),
    PAKISTAN("PK", "Pakistan", "+92"),
    PALESTINE("PS", "Palestyna", "+970"),
    SINGAPORE("SG", "Singapur", "+65"),
    SRI_LANKA("LK", "Sri Lanka", "+94"),
    SYRIA("SY", "Syria", "+963"),
    TAJIKISTAN("TJ", "Tadżykistan", "+992"),
    THAILAND("TH", "Tajlandia", "+66"),
    EAST_TIMOR("TL", "Timor Wschodni", "+670"),
    TURKMENISTAN("TM", "Turkmenistan", "+993"),
    UZBEKISTAN("UZ", "Uzbekistan", "+998"),
    VIETNAM("VN", "Wietnam", "+84"),
    UNITED_ARAB_EMIRATES("AE", "Zjednoczone Emiraty Arabskie", "+971"),

    // Africa
    ALGERIA("DZ", "Algieria", "+213"),
    ANGOLA("AO", "Angola", "+244"),
    BENIN("BJ", "Benin", "+229"),
    BOTSWANA("BW", "Botswana", "+267"),
    BURKINA_FASO("BF", "Burkina Faso", "+226"),
    BURUNDI("BI", "Burundi", "+257"),
    CHAD("TD", "Czad", "+235"),
    DR_CONGO("CD", "Demokratyczna Republika Konga", "+243"),
    DJIBOUTI("DJ", "Dżibuti", "+253"),
    EGYPT("EG", "Egipt", "+20"),
    ERITREA("ER", "Erytrea", "+291"),
    ESWATINI("SZ", "Eswatini", "+268"),
    ETHIOPIA("ET", "Etiopia", "+251"),
    GABON("GA", "Gabon", "+241"),
    GAMBIA("GM", "Gambia", "+220"),
    GHANA("GH", "Ghana", "+233"),
    GUINEA("GN", "Gwinea", "+224"),
    GUINEA_BISSAU("GW", "Gwinea Bissau", "+245"),
    EQUATORIAL_GUINEA("GQ", "Gwinea Równikowa", "+240"),
    CAMEROON("CM", "Kamerun", "+237"),
    KENYA("KE", "Kenia", "+254"),
    COMOROS("KM", "Komory", "+269"),
    CONGO("CG", "Kongo", "+242"),
    LESOTHO("LS", "Lesotho", "+266"),
    LIBERIA("LR", "Liberia", "+231"),
    LIBYA("LY", "Libia", "+218"),
    MADAGASCAR("MG", "Madagaskar", "+261"),
    MALAWI("MW", "Malawi", "+265"),
    MALI("ML", "Mali", "+223"),
    MOROCCO("MA", "Maroko", "+212"),
    MAURITANIA("MR", "Mauretania", "+222"),
    MAURITIUS("MU", "Mauritius", "+230"),
    MOZAMBIQUE("MZ", "Mozambik", "+258"),
    NAMIBIA("NA", "Namibia", "+264"),
    NIGER("NE", "Niger", "+227"),
    NIGERIA("NG", "Nigeria", "+234"),
    SOUTH_AFRICA("ZA", "Południowa Afryka", "+27"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "Republika Środkowoafrykańska", "+236"),
    CAPE_VERDE("CV", "Republika Zielonego Przylądka", "+238"),
    RWANDA("RW", "Rwanda", "+250"),
    SENEGAL("SN", "Senegal", "+221"),
    SEYCHELLES("SC", "Seszele", "+248"),
    SIERRA_LEONE("SL", "Sierra Leone", "+232"),
    SOMALIA("SO", "Somalia", "+252"),
    SUDAN("SD", "Sudan", "+249"),
    SOUTH_SUDAN("SS", "Sudan Południowy", "+211"),
    SAO_TOME_AND_PRINCIPE("ST", "Święty Tomasz i Książęca", "+239"),
    TANZANIA("TZ", "Tanzania", "+255"),
    TOGO("TG", "Togo", "+228"),
    TUNISIA("TN", "Tunezja", "+216"),
    UGANDA("UG", "Uganda", "+256"),
    IVORY_COAST("CI", "Wybrzeże Kości Słoniowej", "+225"),
    ZAMBIA("ZM", "Zambia", "+260"),
    ZIMBABWE("ZW", "Zimbabwe", "+263"),

    // Oceania
    AUSTRALIA("AU", "Australia", "+61"),
    FIJI("FJ", "Fidżi", "+679"),
    KIRIBATI("KI", "Kiribati", "+686"),
    MICRONESIA("FM", "Mikronezja", "+691"),
    NAURU("NR", "Nauru", "+674"),
    NEW_ZEALAND("NZ", "Nowa Zelandia", "+64"),
    PALAU("PW", "Palau", "+680"),
    PAPUA_NEW_GUINEA("PG", "Papua-Nowa Gwinea", "+675"),
    SAMOA("WS", "Samoa", "+685"),
    TONGA("TO", "Tonga", "+676"),
    TUVALU("TV", "Tuvalu", "+688"),
    VANUATU("VU", "Vanuatu", "+678"),
    MARSHALL_ISLANDS("MH", "Wyspy Marshalla", "+692"),
    SOLOMON_ISLANDS("SB", "Wyspy Salomona", "+677");

    private final String isoCode;
    private final String name;
    private final String phoneSuffix;

    Country(String isoCode, String name, String phoneSuffix) {
        this.isoCode = isoCode;
        this.name = name;
        this.phoneSuffix = phoneSuffix;
    }

    public static Optional<Country> getByIsoCode(String isoCode) {
        return Arrays.stream(Country.values()).filter(c -> c.isoCode.equals(isoCode)).findFirst();
    }
}